### ISSUE TITLE
Click in window deletes all available redirects

### ISSUE THREAD

**Issue by chrfickinger** [distantnative/retour-for-kirby#221]
## Describe the bug
After editing an redirect entry in drawer, the file `redirects.yml` with a couple of entries was cleared completely and looked like this:
```
routes: [ ]
schema: 3.0.0
```
This behavior has already occurred twice the last days. Once after clicking on the check icon in the title bar of the drawer and once when clicking outside the drawer (which also closes the window). After restoring the `redirects.yml` via git all the hits were also back. So it obviously only affects the redirects and not the logs.

## Steps to reproduce
not reproducible

## Specifications

  - Retour version: 3.0
  - Kirby version: 3.5.1
  - Retour config options:
       ` 'distantnative.retour.config' 	=> 'site/config/plugins/retour/projectname.redirects.yml',`
	`'distantnative.retour.database' => 'site/logs/retour/projectname.logs.sqlite',`
	`'distantnative.retour.logs' => true,`
	`'distantnative.retour.deleteAfter' => false,`
	`'distantnative.retour.ignore' => []`

**Comment by chrfickinger** [comment]
### Additional info to reproduce:
It seems it is a caching problem in Chrome 88 on Windows 10. 
For some reasons chrome doesn't always seem to succeed in loading the existing entries and an empty table is displayed. If afterwards a new entry is added or clicked outside the drawer, the existing redirects are overwritten with the empty content.
I hope this helps a little bit to debug the behavoir.

**Comment by chrfickinger** [comment]
Obviously it's not just chrome. I just had the same behavior under Firefox 85 on Macos 10.14.6

**Comment by distantnative** [comment]
FYI I'm currently working on a more stable solution for updating the redirect routes data.

**Comment by distantnative** [comment]
I think this should be solved with the upcoming release. 
- Instead of updating/overwriting all redirects when adding/editing/removing a redirect, now individual requests are sent to the backend
- Blocking interaction of the table as long as the altering request and reload of table data has been finished

**Comment by chrfickinger** [comment]
Thank you for letting me know!

**Comment by distantnative** [comment]
I'll release a version with that fix later today.

**Comment by distantnative** [comment]
✅

**Comment by chrfickinger** [comment]
Bug is not yet fixed. It happened again. Let me know if I can share anything to reproduce the behavior.

**Comment by distantnative** [comment]
:(

Any errors in the console?

**Comment by chrfickinger** [comment]
Actually I don't get the point when it happes. I didn't work on the redirects for a while and when I came back to the panel the file was empty again.

**Comment by distantnative** [comment]
Bundling errors under this issue: https://github.com/distantnative/retour-for-kirby/issues/229
